# Generated by Django 4.1.7 on 2023-04-06 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookissue',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookissue',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookIssue',
        ),
    ]
