# Generated by Django 4.1.7 on 2023-04-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_book_bookissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
